version: "3"
services:
  nginx:
    build: ./nginx
    depends_on:
      - backend
      - frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/

  backend:
    platform: linux/x86_64
    build: ./api
    volumes:
      - ./api/:/app/src
      - ./.env:/app/.env.local
    ports:
      - "3001:80"

  frontend:
    build: ./client
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    ports:
      - "3000:3000"